// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID        uuid.UUID
	ClerkID   string
	Email     string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Workflow struct {
	ID           uuid.UUID
	WorkflowName string
	UserID       uuid.UUID
	Nodes        json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
}
