// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error)
	DeleteWorkflowById(ctx context.Context, arg DeleteWorkflowByIdParams) error
	GetActiveWorkflows(ctx context.Context) ([]Workflow, error)
	GetUserById(ctx context.Context, id uuid.UUID) (User, error)
	GetWorkflowById(ctx context.Context, id uuid.UUID) (Workflow, error)
	GetWorkflowMetadataByWorkflowId(ctx context.Context, workflowID uuid.UUID) (WorkflowMetadatum, error)
	GetWorkflowsByUserId(ctx context.Context, userID string) ([]Workflow, error)
	UpdateWorkflowById(ctx context.Context, arg UpdateWorkflowByIdParams) (Workflow, error)
	UpdateWorkflowStatusById(ctx context.Context, arg UpdateWorkflowStatusByIdParams) (Workflow, error)
	UpsertWorkflowMetadata(ctx context.Context, arg UpsertWorkflowMetadataParams) error
}

var _ Querier = (*Queries)(nil)
