// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow_metadata.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const getWorkflowMetadataByWorkflowId = `-- name: GetWorkflowMetadataByWorkflowId :one
SELECT workflow_id, edges, in_degree, start_nodes, created_at, updated_at FROM workflow_metadata WHERE workflow_id = $1
`

func (q *Queries) GetWorkflowMetadataByWorkflowId(ctx context.Context, workflowID uuid.UUID) (WorkflowMetadatum, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowMetadataByWorkflowId, workflowID)
	var i WorkflowMetadatum
	err := row.Scan(
		&i.WorkflowID,
		&i.Edges,
		&i.InDegree,
		&i.StartNodes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertWorkflowMetadata = `-- name: UpsertWorkflowMetadata :exec
INSERT INTO workflow_metadata (
    workflow_id,
    edges,
    in_degree,
    start_nodes,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, NOW(), NOW()
)
ON CONFLICT (workflow_id)
DO UPDATE SET
    edges = EXCLUDED.edges,
    in_degree = EXCLUDED.in_degree,
    start_nodes = EXCLUDED.start_nodes,
    updated_at = NOW()
`

type UpsertWorkflowMetadataParams struct {
	WorkflowID uuid.UUID
	Edges      json.RawMessage
	InDegree   json.RawMessage
	StartNodes json.RawMessage
}

func (q *Queries) UpsertWorkflowMetadata(ctx context.Context, arg UpsertWorkflowMetadataParams) error {
	_, err := q.db.ExecContext(ctx, upsertWorkflowMetadata,
		arg.WorkflowID,
		arg.Edges,
		arg.InDegree,
		arg.StartNodes,
	)
	return err
}
