// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: workflow.sql

package database

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createWorkflow = `-- name: CreateWorkflow :one
INSERT INTO workflow (id, workflow_name, user_id, nodes, edges, status, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, workflow_name, user_id, nodes, edges, status, created_at, updated_at
`

type CreateWorkflowParams struct {
	ID           uuid.UUID
	WorkflowName string
	UserID       string
	Nodes        json.RawMessage
	Edges        json.RawMessage
	Status       WorkflowStatus
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

func (q *Queries) CreateWorkflow(ctx context.Context, arg CreateWorkflowParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, createWorkflow,
		arg.ID,
		arg.WorkflowName,
		arg.UserID,
		arg.Nodes,
		arg.Edges,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkflowName,
		&i.UserID,
		&i.Nodes,
		&i.Edges,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveWorkflows = `-- name: GetActiveWorkflows :many
SELECT id, workflow_name, user_id, nodes, edges, status, created_at, updated_at FROM workflow WHERE status = 'active'
`

func (q *Queries) GetActiveWorkflows(ctx context.Context) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, getActiveWorkflows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowName,
			&i.UserID,
			&i.Nodes,
			&i.Edges,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWorkflowById = `-- name: GetWorkflowById :one
SELECT id, workflow_name, user_id, nodes, edges, status, created_at, updated_at FROM workflow WHERE id = $1
`

func (q *Queries) GetWorkflowById(ctx context.Context, id uuid.UUID) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, getWorkflowById, id)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkflowName,
		&i.UserID,
		&i.Nodes,
		&i.Edges,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkflowsByUserId = `-- name: GetWorkflowsByUserId :many
SELECT id, workflow_name, user_id, nodes, edges, status, created_at, updated_at FROM workflow WHERE user_id = $1
`

func (q *Queries) GetWorkflowsByUserId(ctx context.Context, userID string) ([]Workflow, error) {
	rows, err := q.db.QueryContext(ctx, getWorkflowsByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workflow
	for rows.Next() {
		var i Workflow
		if err := rows.Scan(
			&i.ID,
			&i.WorkflowName,
			&i.UserID,
			&i.Nodes,
			&i.Edges,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkflowById = `-- name: UpdateWorkflowById :one
UPDATE workflow SET nodes = $1, edges = $2, workflow_name = $3, status = $4, updated_at = $5 WHERE id = $6 AND user_id = $7 RETURNING id, workflow_name, user_id, nodes, edges, status, created_at, updated_at
`

type UpdateWorkflowByIdParams struct {
	Nodes        json.RawMessage
	Edges        json.RawMessage
	WorkflowName string
	Status       WorkflowStatus
	UpdatedAt    time.Time
	ID           uuid.UUID
	UserID       string
}

func (q *Queries) UpdateWorkflowById(ctx context.Context, arg UpdateWorkflowByIdParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflowById,
		arg.Nodes,
		arg.Edges,
		arg.WorkflowName,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkflowName,
		&i.UserID,
		&i.Nodes,
		&i.Edges,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkflowStatusById = `-- name: UpdateWorkflowStatusById :one
UPDATE workflow SET status = $1, updated_at = $2 WHERE id = $3 AND user_id = $4 RETURNING id, workflow_name, user_id, nodes, edges, status, created_at, updated_at
`

type UpdateWorkflowStatusByIdParams struct {
	Status    WorkflowStatus
	UpdatedAt time.Time
	ID        uuid.UUID
	UserID    string
}

func (q *Queries) UpdateWorkflowStatusById(ctx context.Context, arg UpdateWorkflowStatusByIdParams) (Workflow, error) {
	row := q.db.QueryRowContext(ctx, updateWorkflowStatusById,
		arg.Status,
		arg.UpdatedAt,
		arg.ID,
		arg.UserID,
	)
	var i Workflow
	err := row.Scan(
		&i.ID,
		&i.WorkflowName,
		&i.UserID,
		&i.Nodes,
		&i.Edges,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
